USE pi_petfeed;

CREATE TABLE
IF NOT EXISTS device
(
	id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    deviceId TEXT NOT NULL,
    password TEXT,
    accessToken TEXT,
    type VARCHAR
(20),
    typeId INTEGER
);

CREATE TABLE
IF NOT EXISTS schedule
(
	id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    day VARCHAR
(20) NOT NULL,
    feedTime TIME NOT NULL,
	amount FLOAT8 NOT NULL,
    synced BOOLEAN DEFAULT FALSE
);

CREATE TABLE
IF NOT EXISTS user (
	id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    name VARCHAR
(40) NOT NULL,
    email VARCHAR
(40) NOT NULL,
    server_id INTEGER NOT NULL
);

CREATE TABLE
IF NOT EXISTS history
(
	id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    schedule_id INTEGER,
	fed BOOLEAN DEFAULT FALSE,
    synced BOOLEAN DEFAULT FALSE,
    amount FLOAT8 NOT NULL,
    feedDateTime DATETIME DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE schedule 
    ADD uploaded BOOLEAN DEFAULT FALSE,
    ADD deleted BOOLEAN DEFAULT FALSE,
    ADD groupId VARCHAR(20),
    ADD petId INTEGER,
    ADD uId VARCHAR(20) UNIQUE,
    ADD serverId INTEGER DEFAULT NULL;